# Generated by Django 3.2 on 2022-06-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='composer',
            field=models.CharField(blank=True, max_length=500, verbose_name='Composer'),
        ),
        migrations.AddField(
            model_name='event',
            name='contributing',
            field=models.CharField(blank=True, max_length=500, verbose_name='Contributing'),
        ),
    ]
