# Generated by Django 3.2 on 2022-06-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220605_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ['ordering'], 'verbose_name': 'EventCategory', 'verbose_name_plural': 'EventCategories'},
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
