# Generated by Django 3.2 on 2022-06-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220605_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
