# Generated by Django 3.2 on 2022-07-03 09:19

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
