# Generated by Django 3.2 on 2022-07-03 09:29

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published_year',
            field=models.IntegerField(default=events.models.current_year, verbose_name='Year of Article'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug'),
        ),
    ]
