# Generated by Django 3.2 on 2022-07-03 09:30

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20220703_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
