# Generated by Django 3.2 on 2022-07-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_published_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, max_length=80, verbose_name='Ticket URL Seite'),
        ),
    ]
