# Generated by Django 3.2 on 2022-07-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_ticket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
