# Generated by Django 3.2 on 2022-07-08 15:35

import datetime
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20220707_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='composer',
            field=models.CharField(blank=True, max_length=500, verbose_name='Komponisten'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Beitragsinhalt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_lead',
            field=models.TextField(blank=True, null=True, verbose_name='Beitrag Lead'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_title',
            field=models.TextField(blank=True, null=True, verbose_name='Beitragstitel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contributing',
            field=models.CharField(blank=True, max_length=500, verbose_name='Mitwirkende'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='events/images/', verbose_name='Beitragsbild'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Bildbezeichnung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Titel Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published_year',
            field=models.IntegerField(default=2022, verbose_name='Year of Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Zusätzl. Veranstaltungstext'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_url',
            field=models.URLField(blank=True, max_length=80, verbose_name='Ticketseite URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, db_index=True, null=True, verbose_name='Uhrzeit'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=80, verbose_name='Spielort'),
        ),
    ]
