# Generated by Django 3.2 on 2022-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20220708_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content_lead',
            field=models.TextField(blank=True, null=True, verbose_name='Beitragslead'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published_year',
            field=models.IntegerField(default=2022, verbose_name='Jahr der Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
