# Generated by Django 3.2 on 2022-07-10 03:59

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='events/images/', verbose_name='Beitragsbild'),
        ),
    ]
