# Generated by Django 3.2 on 2022-09-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program_folder',
            field=models.FileField(blank=True, upload_to='events/programm_folder/%Y/%m/%d/'),
        ),
    ]
