# Generated by Django 3.2 on 2022-09-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_event_program_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='program_folder',
            field=models.FileField(blank=True, upload_to='events/programm_folder/%Y/%m/%d/', verbose_name='Programm Folder'),
        ),
    ]
