# Generated by Django 3.2 on 2022-07-13 04:24

import blog.models
from django.db import migrations, models
import django.utils.timezone
import django_quill.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lead_paragraph', models.TextField(blank=True)),
                ('number_of_posts', models.IntegerField(blank=True, null=True)),
                ('content', django_quill.fields.QuillField(verbose_name='Beitragsinhalt')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Beitragsbild')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Blog Post Date')),
                ('published_year', models.IntegerField(default=blog.models.current_year, verbose_name='Year of Article')),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ('-date',),
            },
        ),
    ]
