# Generated by Django 3.2 on 2022-07-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Bildbezeichnung'),
        ),
    ]
