# Generated by Django 3.2 on 2022-07-12 04:21

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Text Startseite')),
            ],
            options={
                'verbose_name': 'Index Text',
                'verbose_name_plural': 'Index Texts',
            },
        ),
    ]
