# Generated by Django 3.2 on 2024-09-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(),
        ),
    ]
